name: "secret-vault-github-action-plugin"
description: "Delinea DevOps Secrets Vault (DSV) GitHub Actions Plugin allows you to access and reference your Secrets data available for use in GitHub Actions"

inputs:
  server:
    required: true
  clientId:
    required: true
  clientSecret:
    required: true
  setEnv:
    required: true
  retrieve:
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - --server=${{ inputs.server }}
    - --clientId=${{ inputs.clientId }}
    - --clientSecret=${{ inputs.clientSecret }}
    - --setEnv=${{ inputs.setEnv }}
    - --retrieve=${{ inputs.retrieve }}